### ISSUE TITLE
Nachricht an ALLE (Chat)

### ISSUE THREAD

**Issue by leodejevga** [leodejevga/breathy#6]
Hallo alle zusammen.
Ich nutze mal diese Issue als Chat für uns alle damit auch wirklich ALLE alles mitkriegen 👍 

Ich habe im [commit](https://github.com/leodejevga/breathy/commit/69d0dcfde3ee21509b01e36e77e429133eb5a959) Javadoc und TODOs hinzugefüt...

**Comment by leodejevga** [comment]
Also Leute,
Die App hat, wie schon gesagt, drei Projekte (app, source, audioSurf). Projekt app ist main Projekt und die Aktivity 'Menu' ist die, die ganz am Anfang startet. Pprojekt audiosurf ist unser Spiel. Dieser hat einen GameHandler sozusagen, der alles starten kann: Spiel, Optionen, Preview... Source beinhaltet alles was alle Projekte benötigen Coins zum Beispiel. Außerdem liegen dort Interfaces und abstrakte Implementationen davon. Diese helfen dem Programmierer eine Struktur zu behalten um das Spiel soweit zu programmieren, dass es von der app akzeptiert wird.
Jedes Projekt (bis auf Source) muss eine statische Backend Klasse haben, die den Hintergrundablauf regelt. Diese müssen eine init() methode enthalten die Backends initialisieren.

Jedes Projekt (bis auf source) haben Activity Ordner wo Activites hinterlegt werden.

Wenn ihr jetzt eure Aufgaben macht, dafür gibt es den Branch Aufgaben 
Bevor man anfängt, nicht vergessen zu pullen!

**Comment by leodejevga** [comment]
Ich habe neue Aufgaben Verteil. Diese müssen im Meilenstein Fundament erledigt werden 👍  das heißt bis zum ersten März.

**Comment by iwnfubb** [comment]
yolo
